spring:
  profiles:
    active:
      - dev
---
server:
  port: 9011
spring:
  profiles: dev 
  application:
    name: config-client-dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/  
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true 
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
lwf: gsyxka!


---
server:
  port: 9012
spring:
  profiles: test 
  application:
    name: config-client-test
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/ 
    fetch-registry: true
    register-with-eureka: true  
  instance:
    prefer-ip-address: true 
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
